title: Keep the Rhythm
description: >-
  An Obsidian plugin that helps you maintain a consistent writing habit by
  tracking your daily word count, setting writing goals, and visualizing
  your progress through a heatmap and customizable code blocks.

baseurl: "/keep-the-rhythm"
url: "https://benjaminezequiel.github.io"

theme: minima

header_pages:
  - installation.md
  - usage.md
  - code-blocks.md
  - settings.md
  - faq.md

github_username: benjaminezequiel

exclude:
  - README.md
